# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2821a029f58c0f9a0e54cbcbe4bb61bd972e74485cd7e58da08e29ddac758a8d126d2ff4efc8d97cc997b93a24707956fcebaf1fb7f5a1c521a51cc091dfe485

test:
  secret_key_base: e4c5fa51c94f8569b8b642c3098a61879ee1715d4ab936868a0fcd8d9c873fffadbb44d9b7545836aec17060da3e936073eafc8ab66c57ab8865ec6547388072

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
